<?php

use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_install().
 */
function fkr_rapyd_install() {
  if (!FieldStorageConfig::loadByName('commerce_order', 'field_giftcard_code')) {
    FieldStorageConfig::create([
      'field_name'  => 'field_giftcard_code',
      'entity_type' => 'commerce_order',
      'type'        => 'string',
      'cardinality' => 1,
    ])->save();
  }

  if (!FieldConfig::loadByName('commerce_order', 'default', 'field_giftcard_code')) {
    FieldConfig::create([
      'field_name'  => 'field_giftcard_code',
      'entity_type' => 'commerce_order',
      'bundle'      => 'default',
      'label'       => 'Gift Card Code',
    ])->save();
  }
}

/**
 * Implements hook_uninstall().
 */
function fkr_rapyd_uninstall() {
  $field = FieldConfig::loadByName('commerce_order', 'default', 'field_giftcard_code');
  if ($field) {
    $field->delete();
  }
  $storage = FieldStorageConfig::loadByName('commerce_order', 'field_giftcard_code');
  if ($storage) {
    $storage->delete();
  }
}
